services:
  - type: web
    name: streamlit-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run trial2.py --server.port $PORT --server.address 0.0.0.0
